apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome to Kubernetes!</h1>
    <body>
    This is Nginx Server running from the pod
    </body>
    </html>